### ISSUE TITLE
Create integration tests

### ISSUE THREAD

**Issue by mmahut** [blockfrost/blockfrost-websocket-link#232]
Create a set of integration tests for blockfrost-websocket-link.

Ideally a test would run blockfrost-websocket-link againts the production Blockfrost and do some testings, resolving address, watch for a block etc.

For preview/preprod, even submitting a TX and watching it appears on chain.

**Comment by slowbackspace** [comment]
Just few things to consider:
- there are unit tests for each method with mocked blockfrost endpoints, if we remove the mocks they could become integration tests? eg. [GET_ACCOUNT_INFO]()
- there is[ a simple implementation of websocket client](https://github.com/blockfrost/blockfrost-websocket-link/blob/master/src/utils/websocket-client.ts) for communicating with wslink. We've used it [to simulate real world load from a wallet](https://github.com/blockfrost/blockfrost-websocket-link/blob/master/src/scripts/performance/index.ts). So maybe this is also something that could be leveraged for full blown integration tests by adding few asserts

**Comment by bslabiak** [comment]
@slowbackspace 
-  It will probably require tweaking around fixtures and more flexible assertions and trigger tests by using ws layer not method directly.
I think we should keep units to have gateway before testing "live" integration. 
On the other hand it is true that tests will be very similar. 
-  Thank you! I have started on reimplementing very similar ws approach. I will try to reuse this one.

**Comment by bslabiak** [comment]
First implementation done in:
[#250](https://github.com/blockfrost/blockfrost-websocket-link/pull/250)
[#277](https://github.com/blockfrost/blockfrost-websocket-link/pull/277)
