### ISSUE TITLE
Option to include transaction CBOR in `GET_ACCOUNT_INFO` and `GET_TRANSACTION`

### ISSUE THREAD

**Issue by slowbackspace** [blockfrost/blockfrost-websocket-link#253]
The `GET_ACCOUNT_INFO` endpoint, when the `details` parameter is set to `txs`, provides a paginated list of account transactions. With the [addition of transaction CBOR in events from `SUBSCRIBE_ADDRESS`](https://github.com/blockfrost/blockfrost-websocket-link/pull/245), extending `GET_ACCOUNT_INFO` and `GET_TRANSACTION` to support CBOR data would complete the integration of tx CBOR across all relevant wslink messages

**Comment by mmahut** [comment]
Ah, sorry, I did miss this in the original feature request. This is of course needed for any discovery.

**Comment by iccicci** [comment]
Done with #270 and #271
