### ISSUE TITLE
GET_PROTOCOL_PARAMETERS for retrieving latest protocol params

### ISSUE THREAD

**Issue by slowbackspace** [blockfrost/blockfrost-websocket-link#254]
Currently the clients can't build a transaction just by using the data provided by wslink - for setting TTL the client needs to know current slot, also various protocol params are needed during tx builder setup (pool_deposit, key_deposit, ,coins_per_utxo_byte, max_value_size, min_fee_a, min_fee_b). We could exposes needed information by implementing new command for retrieving [latest protocol params](https://docs.blockfrost.io/#tag/cardano--epochs/GET/epochs/latest/parameters).

Note: After implementing this we could deprecate `ESTIMATE_FEE` msg since the information would be included in the new msg.

**Comment by iccicci** [comment]
Done with #272
